[package]
name = "tui-macros"
description = "Placeholder for moving ratatui-macros to a separate crate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
